# Generated by Django 3.1.4 on 2021-05-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
