# Generated by Django 3.1.4 on 2021-05-18 08:43

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#00FF00', 'lime'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow')], default='#FFFFFF', max_length=18)),
                ('basic_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.basicproduct')),
            ],
        ),
    ]
