# Generated by Django 3.1.4 on 2021-06-23 16:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20210604_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='screen',
            new_name='graphics',
        ),
        migrations.AlterField(
            model_name='basicphone',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#00FF00', 'lime'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow'), ('#575757', 'grey')], default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='extraphone',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#00FF00', 'lime'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow'), ('#575757', 'grey')], default='#FFFFFF', max_length=18),
        ),
    ]
